name: CI Log Analyzer

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test-log-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python3 --version

      - name: Exécuter log_analyzer.py
        run: |
          if [ ! -f log.txt ]; then
            echo "2025-05-31 12:00:00 INFO  Test CI" > log.txt
            echo "2025-05-31 12:00:01 ERROR Test CI" >> log.txt
          fi
          python3 log_analyzer.py log.txt rapport_ci.txt
          echo "=== Affichage du rapport généré CI ==="
          cat rapport_ci.txt

      - name: Upload rapport en artifact
        uses: actions/upload-artifact@v3
        with:
          name: rapport-logs
          path: rapport_ci.txt